#!/usr/bin/python

from global_vars import *
from package import *
from util import *
from opts import *


help_ = open(f'{ROOT_DIR}/info', 'r').read()

if __name__ == '__main__':
    parse_opt_args()
    parse_config_file()
    onstart_log()

    argc = len(argv)

    if argc == 1:
        print(help_)
        exit()

    if argc == 2:
        if argv[1] not in ['install', 'search', 'remove', 'update', 'clean']:
            print(f'Invalid operation: {argv[1]}')
        elif argv[1] == 'update':
            update()
            if opts['autoupdate']:
                print('warning: updating aurinstall from GitHub enabled.')
                update_script()
        elif argv[1] == 'clean':
            clean()
        else:
            print(f'Please provide an argument for operation: {argv[1]}')

    elif argc >= 3:
        if argv[1] == 'clean':
            clean()
        if argv[1] == 'install':
            install_packages(argv[2:])

        elif argv[1] == 'search':
            search_package(argv[2:])

        elif argv[1] == 'remove':
            remove_packages(argv[2:])
    else:
        print(f'invalid arguments: {argv}')
